name: Daily AQI Fetcher

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC = 8 AM Pakistan time
  workflow_dispatch:

jobs:
  run-aqi-fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from GitHub secret
        run: echo "${{ secrets.AQI_FETCHER_SECRETS }}" > .env

      - name: Run main.py
        run: python main.py
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Upload CSV to GitHub Actions artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: lahore-aqi-csv
          path: lahore_aqi_iqair.csv
